twig:
    file_name_pattern: '*.twig'
    form_themes: [ 'bootstrap_4_horizontal_layout.html.twig' ]

    globals:
        app_region: '%env(resolve:APPLICATION_REGION)%'
        app_version: '%env(resolve:APPLICATION_VERSION)%'

when@test:
    twig:
        strict_variables: true
